### ISSUE TITLE
Deprecation warning due to Node 16

### ISSUE THREAD

**Issue by Piedone** [tunaitis/contributor-map#9]
Node 16 is [now deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, when using this action, you'll see warnings like below under your workflow runs:

![image](https://github.com/tunaitis/contributor-map/assets/1976647/054c75b6-7ab0-471a-ac60-92de8bb8f8d0)

@tunaitis could you look into this, please?

**Comment by Piedone** [comment]
@tunaitis perhaps you aren't really maintaining this action, but if you do, could you please check out this and my other new issues?

We're using Contributor Map with Orchard Core [here](https://docs.orchardcore.net/en/latest/docs/community/contributors/Map/) BTW, thank you!

**Comment by tunaitis** [comment]
Updated, thanks for using this action!

**Comment by Piedone** [comment]
That was quick, thank you very much! Updated the action's reference for Orchard Core too: https://github.com/OrchardCMS/OrchardCore/pull/15619/files#diff-5c25e809a16b528031d2861d3ff07ceba311fc28ebc72ca3038355d467576df9
